### ISSUE TITLE
Make datasets public?

### ISSUE THREAD

**Issue by lewtun** [GAIR-NLP/MathPile#1]
Hello, thank you for producing this great resource for pretraining! I tried to access the datasets, but the URL returns a 404: https://huggingface.co/datasets/GAIR/MathPile

Do you have plans to make the datasets public soon?

Thank you!

**Comment by SinclairCoder** [comment]
Hi, the dataset is being uploaded on huggingface and will be available in a few hours.

**Comment by SinclairCoder** [comment]
Hi, our MathPile is available at https://huggingface.co/datasets/GAIR/MathPile

**Comment by lewtun** [comment]
Thank you!
