### ISSUE TITLE
Dataset code

### ISSUE THREAD

**Issue by StellaAthena** [GAIR-NLP/MathPile#4]
There does not appear to be any code related to how the dataset was collected, filtered, and cleaned. When is that going to be released?

**Comment by SinclairCoder** [comment]
Thank you very much for your valuable feedback. 

We are currently dedicating our efforts to refining our datasets and enhancing the quality of our data, alongside progressing with model training. Please rest assured that the release of the preprocessed code is on our agenda. We are diligently working towards making it available soon. Your patience and understanding in this matter are greatly appreciated.

**Comment by SinclairCoder** [comment]
Scripts for preprocessing and global data processing have been updated. Please feel free to take a look at it.
