### ISSUE TITLE
data in modelscope for more convenient to download?

### ISSUE THREAD

**Issue by foocker** [GAIR-NLP/MathPile#5]
[modelscope](https://www.modelscope.cn/home)

**Comment by SinclairCoder** [comment]
Thanks for your feedback. We're thinking about it. You can also download it through the [HF mirror](https://hf-mirror.com/) if issued by the network issue.

**Comment by BlackBearBiscuit** [comment]
+1, please upload it to modelscope!

**Comment by SinclairCoder** [comment]
hi, MathPile is also available at Wisemodel now! Feel free to download it!  

https://wisemodel.cn/datasets/GAIR/MathPile
https://wisemodel.cn/datasets/GAIR/MathPile_Commercial
