### ISSUE TITLE
original latex source release

### ISSUE THREAD

**Issue by NZ42** [GAIR-NLP/MathPile#6]
Fantastic work, thanks for the release.

Is there any chance you could also release the original latex files? Even just privately. I'm interested in this for a scientific OCR project.

Thanks a lot!

**Comment by NZ42** [comment]
I would also be interested in page-specific mathpix OCR outputs for the textbook subset if those were available too

**Comment by SinclairCoder** [comment]
Thanks for your interest. Unfortunately, the parsing results from the mathpix api are not page-specific, i.e., given a pdf, a parsed doc like markdown will be obtained, which contains the whole content of the pdf, not separated by the page.

**Comment by NZ42** [comment]
Understood! Would it be possible to release them still? And what about the original LaTeX files? Thanks a lot!

**Comment by SinclairCoder** [comment]
We can release these latex files. Before that, could I know what you intended to use about these latex files, and is it for commercial purposes? Thanks for your understanding.

**Comment by NZ42** [comment]
That would be lovely! My intended use case is scientific OCR. I would like
to see if I can handle the mapping from page image to latex for the
creation of an open-source scientific OCR dataset -- no commercial
applications planned, just research. Thank you!

**Comment by SinclairCoder** [comment]
Hi, you can download it from the following sharing link. Please DO NOT use it for commercial purposes, just for research. And, feel free to cite our [MathPile paper](https://arxiv.org/abs/2312.17120)!  :)

https://drive.google.com/file/d/1m1UIhpXT3_9LR61BN3JB0xyUJZqVzumR/view?usp=sharing

**Comment by NZ42** [comment]
Thank you!
